config/routes.rb
Rails.application.routes.draw do
  root "places#index"

  get("/", { :controller => "places", :action => "index" })
  resources "entries"
  resources "places"
  resources "sessions"
  resources "users"

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :place
  belongs_to :user
    
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  helper_method :current_user, :logged_in?

  def current_user
    puts "------------------ code before every request ------------------"
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def require_login
    redirect_to login_path unless logged_in?
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :require_login

  def new
    @entry = Entry.new
  end

  def create
    @place = Place.find(params[:place_id])
    @entry = @place.entries.build(entry_params)
    @entry.user = current_user

    if @entry.save
      redirect_to place_path(@place)
    else
      render "entries/new"
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description, :occurred_on, :image)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @entries = @place.entries.where(user: current_user)
    @entry = Entry.new
  end

  def new
  end

  def create
    @place = Place.new
    @place["name"] = params["name"]
    @place.save
    redirect_to "/places"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to places_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to places_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= form_with model: @entry, url: entries_path, local: true, multipart: true do |f| %>
  <%= hidden_field_tag :place_id, params[:place_id] %>

  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :occurred_on %>
    <%= f.date_field :occurred_on, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <%= f.submit "Save Entry", class: "btn btn-success" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tacostagram Final</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Optional custom styles -->
    <link rel="stylesheet" href="/stylesheets/application.css">
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "Home", root_path, class: "navbar-brand" %>
        <div class="collapse navbar-collapse justify-content-end">
          <ul class="navbar-nav">
            <% if logged_in? %>
              <li class="nav-item">
                <span class="nav-link text-muted">Logged in as <%= current_user.username %></span>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", login_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Signup", signup_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Flash messages -->
    <div class="container mt-3">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places</h1>

<ul>
  <% for place in @places %>
    <li><a href="/places/<%= place["id"] %>"><%= place["name"] %></a></li>
  <% end %>
</ul>

<p>
  <a href="/places/new">New place</a>
</p>

app/views/places/new.html.erb
<h1>New Place</h1>

<form action="/places" method="post">
  <p>
    <label for="name_input">Name</label>
    <input type="text" name="name" id="name_input">
  </p>

  <button>Save</button>
</form>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<h2>My Entries</h2>

<div class="row">
  <% @entries.each do |entry| %>
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100">
        <% if entry.image.attached? %>
          <%= image_tag entry.image, class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= entry.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= entry.occurred_on %></h6>
          <p class="card-text"><%= entry.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% if logged_in? %>
  <p>
    <%= link_to "New Entry", new_entry_path(place_id: @place.id), class: "btn btn-primary" %>
  </p>
<% end %>

<p>
  <%= link_to "Back to All Places", places_path, class: "btn btn-secondary" %>
</p>

app/views/users/new.html.erb
<h1>New User Account</h1>

<%= form_with model: @user, url: signup_path, local: true do |f| %>
  <div class="mb-3">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <%= f.submit "Sign Up", class: "btn btn-primary" %>
<% end %>